/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as protectedUsersIndexRouteImport } from './routes/(protected)/users/index'
import { Route as protectedSettingsIndexRouteImport } from './routes/(protected)/settings/index'
import { Route as protectedSessionsIndexRouteImport } from './routes/(protected)/sessions/index'
import { Route as protectedDashboardIndexRouteImport } from './routes/(protected)/dashboard/index'
import { Route as protectedAppsIndexRouteImport } from './routes/(protected)/apps/index'

const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedUsersIndexRoute = protectedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSettingsIndexRoute = protectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSessionsIndexRoute = protectedSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDashboardIndexRoute = protectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedAppsIndexRoute = protectedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => protectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/apps/': typeof protectedAppsIndexRoute
  '/dashboard/': typeof protectedDashboardIndexRoute
  '/sessions/': typeof protectedSessionsIndexRoute
  '/settings/': typeof protectedSettingsIndexRoute
  '/users/': typeof protectedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/apps': typeof protectedAppsIndexRoute
  '/dashboard': typeof protectedDashboardIndexRoute
  '/sessions': typeof protectedSessionsIndexRoute
  '/settings': typeof protectedSettingsIndexRoute
  '/users': typeof protectedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/(protected)/apps/': typeof protectedAppsIndexRoute
  '/(protected)/dashboard/': typeof protectedDashboardIndexRoute
  '/(protected)/sessions/': typeof protectedSessionsIndexRoute
  '/(protected)/settings/': typeof protectedSettingsIndexRoute
  '/(protected)/users/': typeof protectedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/$'
    | '/auth/sign-in'
    | '/apps/'
    | '/dashboard/'
    | '/sessions/'
    | '/settings/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/auth/sign-in'
    | '/apps'
    | '/dashboard'
    | '/sessions'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/(protected)'
    | '/api/$'
    | '/auth/sign-in'
    | '/(protected)/apps/'
    | '/(protected)/dashboard/'
    | '/(protected)/sessions/'
    | '/(protected)/settings/'
    | '/(protected)/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/users/': {
      id: '/(protected)/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof protectedUsersIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/settings/': {
      id: '/(protected)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof protectedSettingsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/sessions/': {
      id: '/(protected)/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof protectedSessionsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/': {
      id: '/(protected)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedDashboardIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/apps/': {
      id: '/(protected)/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof protectedAppsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface protectedRouteRouteChildren {
  protectedAppsIndexRoute: typeof protectedAppsIndexRoute
  protectedDashboardIndexRoute: typeof protectedDashboardIndexRoute
  protectedSessionsIndexRoute: typeof protectedSessionsIndexRoute
  protectedSettingsIndexRoute: typeof protectedSettingsIndexRoute
  protectedUsersIndexRoute: typeof protectedUsersIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedAppsIndexRoute: protectedAppsIndexRoute,
  protectedDashboardIndexRoute: protectedDashboardIndexRoute,
  protectedSessionsIndexRoute: protectedSessionsIndexRoute,
  protectedSettingsIndexRoute: protectedSettingsIndexRoute,
  protectedUsersIndexRoute: protectedUsersIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
